defaults:
  - model: temporal # "gpt2_minimal", "gpt2_medium", "gpt2_large", "gpt2_xl"
  - data: default
  - tokenizer: exponential
  - dataset: augmented
  - logging: pretraining
  - lr: pretraining
  - optimizer: default
  - tasks: subsequence
  - _self_

out_dir: 'checkpoints'
eval_interval: 500

eval_iters: 100
eval_only: false  # if True, script exits right after the first eval
always_save_checkpoint: false  # if True, always save a checkpoint after each eval
init_from: 'scratch'  # 'scratch' or 'resume' or 'midi-gpt2*'
task: multi_with_composer

loss_masking: pretraining

ddp:
  backend: 'nccl'  # 'nccl', 'gloo', etc.

system:
  device: 'cuda'  # examples: 'cpu', 'cuda', 'cuda:0', 'cuda:1' etc., or try 'mps' on macbooks
  dtype: 'float16'  # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
  compile: true  # use PyTorch 2.0 to compile the model to be faster
  data_workers: 4
