decay_lr: false  # whether to decay the learning rate
warmup_iters: 1000  # how many steps to warm up for
lr_decay_iters: ${optimizer.max_iters}  # should be ~= max_iters per Chinchilla
min_lr: 3e-5  # minimum learning rate, should be ~= learning_rate/10 per Chinchilla
learning_rate: 3e-5  # max learning rate
