# whether to decay the learning rate
decay_lr: true

# how many steps to warm up for
warmup_iters: 50

# should be ~= max_iters per Chinchilla
lr_decay_iters: 400

# minimum learning rate, should be ~= learning_rate/10 per Chinchilla
min_lr: 1e-4

# max learning rate
learning_rate: 3e-3
