- class: BottomLineMasking
  param_range:
    - n_repetitions: 1
    - n_repetitions: 2
    - n_repetitions: 5

- class: TopLineMasking
  param_range:
    - n_repetitions: 1
    - n_repetitions: 2
    - n_repetitions: 3

- class: LowNotesMasking
  param_range:
    - n_notes: 3
    - n_notes: 5
    - n_notes: 10
    - n_notes: 15
    - n_notes: 20

- class: HighNotesMasking
  param_range:
    - n_notes: 3
    - n_notes: 5
    - n_notes: 10
    - n_notes: 15
    - n_notes: 20

- class: ShortNotesMasking
  param_range:
    - n_notes: 3
    - n_notes: 5
    - n_notes: 10
    - n_notes: 15
    - n_notes: 20

- class: LongNotesMasking
  param_range:
    - n_notes: 3
    - n_notes: 5
    - n_notes: 10
    - n_notes: 15
    - n_notes: 20

- class: StrideMasking
  param_range:
    - stride: 1
    - stride: 2
    - stride: 3
    - stride: 5
    - stride: 6
    - stride: 8
    - stride: 10
    - stride: 15
    - stride: 20
