# ~25.3M parameters with 219 vocab size
n_layer: 2
n_head: 2
n_embd: 64
dropout: 0.0  # for pretraining 0 is good, for finetuning try 0.1+
bias: false  # do we use bias inside LayerNorm and Linear layers?
context_size: ${data.context_size}
